//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSaludApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DIRESAEntities1 : DbContext
    {
        public DIRESAEntities1()
            : base("name=DIRESAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spSeguimientoCred_Result> spSeguimientoCred(string textobuscar2)
        {
            var textobuscar2Parameter = textobuscar2 != null ?
                new ObjectParameter("textobuscar2", textobuscar2) :
                new ObjectParameter("textobuscar2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSeguimientoCred_Result>("spSeguimientoCred", textobuscar2Parameter);
        }
    }
}
